apiVersion: v1
kind: Service
metadata:
  name: gestion-etudiants
  labels:
    app: gestion-etudiants
spec:
  type: NodePort
  selector:
    app: gestion-etudiants
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
